import {base} from './program.js?v=3.18.0';
export const DAYS=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
export function validDate(s){return typeof s==='string' && /^\d{4}-\d{2}-\d{2}$/.test(s) && !isNaN(Date.parse(s)) && new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s;}
export const stamp=s=>Date.parse(s+'T00:00:00Z');
export const addDays=(s,n)=>new Date(stamp(s)+n*86400000).toISOString().slice(0,10);
export function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export const weekday=s=>(new Date(stamp(s)).getUTCDay()+6)%7;
export function cycle(date,start){if(date<start)return null;const anchor=addDays(start,(7-weekday(start))%7);if(date<anchor)return {week:1,number:0,day:DAYS[weekday(date)],partial:true};const offset=Math.floor((stamp(date)-stamp(anchor))/86400000);return {week:Math.floor(offset/7)%4+1,number:Math.floor(offset/28)+1,day:DAYS[weekday(date)]};}
export const weekSaturday=date=>addDays(date,5-weekday(date));
export function resolveLongDay(db,date){return (db.longDayOverrides&&db.longDayOverrides[weekSaturday(date)])||db.longDay||'Sat';}
export function plan(date,start,days={},longDay='Sat'){if(days[date]?.tasks)return days[date].tasks;const c=cycle(date,start);return c?base(c.day,c.week,longDay).map((t,i)=>({...t,id:String(i),optional:t.n.includes('optional'),lift:t.n.startsWith('Lift '),ex:t.ex||[]})):[];}
export function status(record,tasks,date,now=today()) {if(date>now || !record || !tasks.length)return 'empty';if(record.missed)return 'missed';const required=tasks.filter(t=>!t.optional);if(required.length&&required.every(t=>record.done?.[t.id]))return 'complete';return tasks.some(t=>record.done?.[t.id])?'partial':'empty';}
export function setCount(ex,week){let n=Number(ex.match(/— (\d)/)?.[1]||3);return week===4?Math.max(1,Math.round(n*.7)):n;}
export function previous(db,date,lift,exercise){
 const current=db.start?plan(date,db.start,db.days,resolveLongDay(db,date)).find(t=>t.id===lift):null;
 const name=current?.ex?.[exercise];
 for(const d of Object.keys(db.days).filter(d=>d<date).sort().reverse()){
  const r=db.days[d];
  if(name){const tasks=plan(d,db.start,db.days,resolveLongDay(db,d));const entries=[...tasks.map(t=>({task:t,sets:r.sets?.[t.id],legacy:r.legacyDetails})),...(r.archivedTasks||[]).slice().reverse()];
   for(const e of entries){if(!e.task.lift)continue;const j=(e.task.ex||[]).findIndex(ex=>exerciseKey(ex)===exerciseKey(name));if(j<0)continue;const sets=e.sets?.[j];if(sets?.some(s=>s.weight!==''||s.reps!==''))return {date:d,sets};const old=e.legacy?.[e.task.id+'-'+j];if(old&&(old.weight||old.reps))return {date:d,sets:[{weight:old.weight||'',reps:old.reps||''}],legacy:true};}
  }else if(weekday(d)===weekday(date)){const sets=r.sets?.[lift]?.[exercise];if(sets?.some(s=>s.weight!==''||s.reps!==''))return {date:d,sets};}
 }return null;
}
export const exerciseKey=ex=>ex.split('—')[0].trim().toLowerCase().replace(/\s+/g,' ');
export function validateTasks(tasks){if(!Array.isArray(tasks)||tasks.length<1||tasks.length>30)throw Error('Use 1–30 daily components.');const ids=new Set();for(const t of tasks){if(!t||typeof t.id!=='string'||['__proto__','constructor','prototype'].includes(t.id)||ids.has(t.id)||typeof t.n!=='string'||!t.n.trim()||t.n.length>500||typeof t.lift!=='boolean'||typeof t.optional!=='boolean'||!Array.isArray(t.ex)||t.ex.length>30||t.ex.some(x=>typeof x!=='string'||x.length>500))throw Error('Invalid workout.');ids.add(t.id);}return tasks;}
export function replaceTask(record,tasks,id,next){validateTasks([{...next,id}]);const original=tasks.find(t=>t.id===id);if(!original)throw Error('Workout not found');record.archivedTasks||=[];if(record.archivedTasks.length>=200)throw Error('Too many archived edits on this date. Export a backup first.');record.archivedTasks.push({session:structuredClone(record.sessions?.[id]||{}),task:structuredClone({...original,ex:original.ex||[]}),sets:structuredClone(record.sets?.[id]||{}),legacy:structuredClone(record.legacyDetails||{})});if(record.sessions)delete record.sessions[id];const oldSets=record.sets?.[id]||{},newSets={};(next.ex||[]).forEach((ex,j)=>{const old=(original.ex||[]).findIndex(x=>exerciseKey(x)===exerciseKey(ex));if(next.lift&&original.lift&&old>=0&&oldSets[old])newSets[j]=structuredClone(oldSets[old]);});record.sets||={};record.sets[id]=newSets;for(const key of Object.keys(record.legacyDetails||{}))if(key.startsWith(id+'-'))delete record.legacyDetails[key];record.tasks=tasks.map(t=>t.id===id?{...next,id}:({...t,ex:t.ex||[]}));record.done[id]=false;record.missed=false;return record;
}
export function migrate(v1,start){const days={};for(let w=1;w<=4;w++)DAYS.forEach((day,i)=>{const r=v1[`${w}-${day}`];if(!r)return;const date=addDays(start,(w-1)*7+i);days[date]={done:{...r.done},notes:r.notes||'',missed:!!r.missed,sets:{},legacyDetails:r.details||{},legacy:true};});return days;}
export function validateBackup(x){if(!x||x.version!==2||!validDate(x.start)||!x.days||typeof x.days!=='object'||Array.isArray(x.days))throw Error('Choose a valid V2 backup.');if(x.longDay!==undefined&&x.longDay!=='Sat'&&x.longDay!=='Sun')throw Error('Invalid long-workout day.');if(x.longDayOverrides!==undefined){if(!x.longDayOverrides||typeof x.longDayOverrides!=='object'||Array.isArray(x.longDayOverrides))throw Error('Invalid long-day overrides.');for(const [k,v] of Object.entries(x.longDayOverrides))if(!validDate(k)||(v!=='Sat'&&v!=='Sun'))throw Error('Invalid long-day override.');}for(const [date,r] of Object.entries(x.days)){if(!validDate(date)||!r||typeof r!=='object'||typeof r.notes!=='string'||!r.done||typeof r.done!=='object')throw Error('Invalid day record.');if(r.sessions){for(const m of Object.values(r.sessions)){if(!m||typeof m!=='object')throw Error('Invalid session');for(const [k,max] of [['minutes',1440],['rpe',10]])if(m[k]!==undefined&&m[k]!==''&&(!Number.isFinite(+m[k])||+m[k]<0||+m[k]>max))throw Error('Invalid session '+k);}}if(r.tasks)validateTasks(r.tasks);if(r.archivedTasks){if(!Array.isArray(r.archivedTasks)||r.archivedTasks.length>200)throw Error('Invalid archived exercises.');for(const entry of r.archivedTasks){validateTasks([entry.task]);if(!entry.sets||typeof entry.sets!=='object')throw Error('Invalid archived sets.');}}if(r.sets)for(const exercises of Object.values(r.sets)){if(!exercises||typeof exercises!=='object')throw Error('Invalid lift.');for(const sets of Object.values(exercises)){if(!Array.isArray(sets)||sets.length>30||sets.some(s=>!s||!['string','number'].includes(typeof s.weight)||!['string','number'].includes(typeof s.reps)))throw Error('Invalid sets.');}}}return x;}
