const A=['Leg press or squat — 3 × 5–8','Bench press or DB press — 3 × 5–8','Chest-supported row — 3 × 6–8','Romanian deadlift — 3 × 6–8','Shoulder press — 2 × 6–10','Biceps — 2 × 8–12','Triceps — 2 × 8–12'];
const B=['DB squat or leg press — 3 × 8–12','Incline DB press — 3 × 8–12','Lat pulldown — 3 × 8–12','Romanian deadlift / hinge — 3 × 8–12','Lateral raise — 3 × 12–15','Biceps — 2 × 10–15','Triceps — 2 × 10–15','Core: cable crunch + Pallof press + plank — 2–3 rounds'];
const C=['Leg press or squat — 2 × 8–10 moderate','Chest press — 3 × 8–12','Row — 3 × 8–12','Hamstring curl — 2 × 10–12','Shoulders — 2 × 10–15','Biceps — 2 × 10–15','Triceps — 2 × 10–15','Core: knee raise + side plank + farmer carry — 2–3 rounds'];
function base(d,w,longDay='Sat'){let t=[{n:'Cold plunge — 6:30 AM'}];const isLong=d===longDay,isWeekendOff=(d==='Sat'||d==='Sun')&&!isLong; if(isLong)t.push({n:'Treadmill (after cold plunge) — easy/optional 10–20 min'}); else if(isWeekendOff)t.push({n:'Treadmill (after cold plunge) — easy 20–30 min, 0–5%'}); else if(d==='Tue'&&(w===2||w===3))t.push({n:'Treadmill (after cold plunge) — easy walk 15–20 min, 0–5% incline'}); else {let inc=['Mon','Wed'].includes(d)?'13–15%':d==='Fri'?'8–10%':'5–8%'; if(w===4)inc=['Mon','Wed'].includes(d)?'5–8%':'3–5%';t.push({n:`Treadmill (after cold plunge) — 30 min @ 3.0 mph, ${inc} incline`})}
if(d==='Mon')t.push({n:'Lift A — Strength'+(w===4?' (deload ~70% volume)':''),ex:A}); if(d==='Wed')t.push({n:'Lift B — Hypertrophy + Core'+(w===4?' (deload ~70% volume)':''),ex:B}); if(d==='Fri')t.push({n:'Lift C — Moderate + Core'+(w===4?' (deload ~65–70% volume)':''),ex:C});
if(d==='Tue'){if(w===2)t.push({n:'Tempo bike',ex:['Warm-up — 10 min easy spin','Tempo — 20 min controlled hard','Cooldown — 10–15 min easy spin']});else if(w===3)t.push({n:'Norwegian 4×4 VO₂max run',ex:['Warm-up — 10 min easy','Interval 1 — 4 min hard, controlled','Active recovery — 3 min easy jog/walk','Interval 2 — 4 min hard','Active recovery — 3 min','Interval 3 — 4 min hard','Active recovery — 3 min','Interval 4 — 4 min hard','Cooldown — 8–10 min easy']});else if(w===4)t.push({n:'Bike — 45–60 min easy'});else t.push({n:'Run — 35–40 min easy Zone 2'});}
if(d==='Thu'){if(w===2)t.push({n:'Run — 35–40 min easy Zone 2'});else if(w===4)t.push({n:'Run — recovery 30–35 min easy'});else t.push({n:'Bike — 60 min Zone 2'});}
if(isLong)t.push({n:w===1?'Long run — 60 min easy':w===2?'Long bike — 90–120 min Zone 2':w===3?'Long run — 70–75 min easy':'Long bike — 60–90 min easy'});if(isWeekendOff)t.push({n:w===4?'Recovery day; basketball only if feeling good':'Basketball OR recovery/mobility'});return t}

export {A,B,C,base};
