import {suggest,applySuggestion} from './suggestions.js?v=3.17.0';
import {plan,resolveLongDay} from './core.js?v=3.17.0';
import {history} from './training.js?v=3.17.0';
export function mountSuggestions(h){const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const dialog=document.createElement('dialog');dialog.id='add-workout-dialog';dialog.innerHTML=`<form id="suggest-form"><h2>Add a workout</h2><p id="suggest-date"></p><label>Workout type<select id="suggest-type"><option value="full">Full-body lifting</option><option value="kettlebell">Kettlebells</option><option value="run">Running</option><option value="bike">Cycling</option><option value="recovery">Recovery / mobility</option><option value="hiit">HIIT Cycle</option><option value="plunge">Cold plunge</option></select></label><label>How to use it<select id="suggest-replace"></select></label><label>Workout name<input id="suggest-name" maxlength="500"></label><label class="remember"><input id="suggest-optional" type="checkbox"> Optional for this day</label><label>Logging style<select id="suggest-kind"><option value="lift">Weights and sets</option><option value="activity">Activity / instructions</option></select></label><label>Exercises or instructions — one per line<textarea id="suggest-lines" rows="7"></textarea></label><p class="muted">Use consistent exercise names to retrieve previous sets. Example: Barbell curl — 2 × 8–12.</p><div id="suggest-history"></div><p id="suggest-error" role="alert"></p><div class="actions"><button id="suggest-save" class="primary" type="submit">Save to this date</button><button id="suggest-close" type="button">Cancel</button></div></form>`;document.body.append(dialog);const $=id=>dialog.querySelector('#'+id);let date,source;
function showHistory(){const lines=$('suggest-lines').value.split('\n').filter(Boolean);$('suggest-history').innerHTML=lines.length?'<b>Previous sets for these exercises</b>'+lines.map(ex=>{const rows=history(h.db(),date,ex).filter(r=>r.date<date),last=rows.at(-1);return `<p class="previous">${esc(ex.split('—')[0])}: ${last?esc(last.date+' · '+last.sets.map(s=>s.weight+' × '+s.reps).join(' · ')):'No matching earlier sets.'}</p>`;}).join(''):'';}
function applyTemplate(){const replace=$('suggest-replace').value;const s=suggest(h.db(),date,{type:$('suggest-type').value,replace});$('suggest-name').value=s.name;$('suggest-optional').checked=s.optional??true;$('suggest-kind').value=s.lift?'lift':'activity';$('suggest-lines').value=s.ex.join('\n');showHistory();}
document.getElementById('add-workout').onclick=()=>{if(h.blocked())return;date=h.date();source=JSON.stringify(plan(date,h.db().start,h.db().days,resolveLongDay(h.db(),date)));$('suggest-date').textContent='For '+date;$('suggest-replace').innerHTML='<option value="">Add an optional extra workout</option>'+plan(date,h.db().start,h.db().days,resolveLongDay(h.db(),date)).map(t=>`<option value="${esc(t.id)}">Replace: ${esc(t.n)}</option>`).join('');$('suggest-error').textContent='';applyTemplate();dialog.showModal();};
$('suggest-type').onchange=applyTemplate;
$('suggest-replace').onchange=applyTemplate;
$('suggest-lines').oninput=showHistory;
$('suggest-form').onsubmit=e=>{e.preventDefault();try{const replace=$('suggest-replace').value;if(h.blocked()||date!==h.date()||source!==JSON.stringify(plan(date,h.db().start,h.db().days,resolveLongDay(h.db(),date))))throw Error('History changed. Close and reopen Add a workout.');const draft={name:$('suggest-name').value,ex:$('suggest-lines').value.split('\n').map(s=>s.trim()).filter(Boolean),lift:$('suggest-kind').value==='lift',optional:$('suggest-optional').checked};if(!draft.name.trim())throw Error('Enter a workout name.');if(!draft.ex.length&&$('suggest-type').value!=='plunge')throw Error('Add at least one exercise or instruction.');const record=structuredClone(h.db().days[date]||{done:{},sets:{},notes:'',missed:false});applySuggestion(record,plan(date,h.db().start,h.db().days,resolveLongDay(h.db(),date)),draft,replace);h.commit(date,record);dialog.close();}catch(e){$('suggest-error').textContent=e.message;}};
$('suggest-close').onclick=()=>dialog.close();
}
