import {suggest,applySuggestion} from './suggestions.js';
import {plan,resolveLongDay} from './core.js';
import {history} from './training.js';
export function mountSuggestions(h){const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const dialog=document.createElement('dialog');dialog.id='add-workout-dialog';dialog.innerHTML=`<form id="suggest-form"><h2>Add a workout</h2><p id="suggest-date"></p><label>Workout type<select id="suggest-type"><option value="full">Full-body lifting</option><option value="kettlebell">Kettlebells</option><option value="run">Running</option><option value="bike">Cycling</option><option value="recovery">Recovery / mobility</option></select></label><label>Time available<select id="suggest-time"><option value="20">20 minutes</option><option value="30" selected>30 minutes</option><option value="45">45 minutes</option><option value="60">60 minutes</option></select></label><label>Equipment<select id="suggest-equipment"><option value="gym">Full gym</option><option value="db">Dumbbells</option><option value="kb">Kettlebells</option><option value="body">Bodyweight only</option></select></label><label>How recovered do you feel?<select id="suggest-recovery"><option value="normal">Okay / some fatigue</option><option value="good">Well recovered</option><option value="low">Tired / sore — keep it easy</option></select></label><label>How to use it<select id="suggest-replace"></select></label><button type="submit">Suggest a plan</button></form><section id="suggest-preview" hidden><h3>Your suggested session</h3><p class="muted">Built from saved workouts and your choices. Review and adjust before saving.</p><div id="suggest-reasons"></div><label>Workout name<input id="suggest-name" maxlength="500"></label><label>Logging style<select id="suggest-kind"><option value="lift">Weights and sets</option><option value="activity">Activity / instructions</option></select></label><label>Exercises or instructions — one per line<textarea id="suggest-lines" rows="7"></textarea></label><p class="muted">Use consistent exercise names to retrieve previous sets. Example: Barbell curl — 2 × 8–12.</p><div id="suggest-history"></div><button id="suggest-save" class="primary">Save to this date</button></section><p id="suggest-error" role="alert"></p><button id="suggest-close">Cancel</button>`;document.body.append(dialog);const $=id=>dialog.querySelector('#'+id);let date,replace,source;
function showHistory(){const lines=$('suggest-lines').value.split('\n').filter(Boolean);$('suggest-history').innerHTML='<b>Previous sets for these exercises</b>'+lines.map(ex=>{const rows=history(h.db(),date,ex).filter(r=>r.date<date),last=rows.at(-1);return `<p class="previous">${esc(ex.split('—')[0])}: ${last?esc(last.date+' · '+last.sets.map(s=>s.weight+' × '+s.reps).join(' · ')):'No matching earlier sets.'}</p>`;}).join('');}
document.getElementById('add-workout').onclick=()=>{if(h.blocked())return;date=h.date();const savedCheck=h.db().days[date]?.checkin; $('suggest-recovery').value=savedCheck&&(savedCheck.energy==='low'||savedCheck.sleep==='poor'||savedCheck.legs==='high'||savedCheck.upper==='high'||savedCheck.pain==='yes')?'low':'normal';$('suggest-equipment').value=h.db().profile?.equipment||'gym';source=JSON.stringify(plan(date,h.db().start,h.db().days,resolveLongDay(h.db(),date)));$('suggest-date').textContent='For '+date;$('suggest-replace').innerHTML='<option value="">Add an optional extra workout</option>'+plan(date,h.db().start,h.db().days,resolveLongDay(h.db(),date)).map(t=>`<option value="${esc(t.id)}">Replace: ${esc(t.n)}</option>`).join('');$('suggest-preview').hidden=true;$('suggest-error').textContent='';dialog.showModal();};
$('suggest-form').oninput=()=>{$('suggest-preview').hidden=true;};
$('suggest-form').onsubmit=e=>{e.preventDefault();replace=$('suggest-replace').value;const s=suggest(h.db(),date,{type:$('suggest-type').value,minutes:Number($('suggest-time').value),equipment:$('suggest-equipment').value,recovery:$('suggest-recovery').value,replace});$('suggest-name').value=s.name;$('suggest-kind').value=s.lift?'lift':'activity';$('suggest-lines').value=s.ex.join('\n');$('suggest-reasons').innerHTML='<ul>'+s.reasons.map(r=>'<li>'+esc(r)+'</li>').join('')+'</ul><p>'+ (replace?'Replaces the selected session; its original logs will be preserved.':'Optional extra: skipping it will not affect your green check.')+'</p>';$('suggest-preview').hidden=false;showHistory();};
$('suggest-lines').oninput=showHistory;
$('suggest-save').onclick=()=>{try{if(h.blocked()||date!==h.date()||source!==JSON.stringify(plan(date,h.db().start,h.db().days,resolveLongDay(h.db(),date))))throw Error('History changed. Close and reopen Add a workout.');const draft={name:$('suggest-name').value,ex:$('suggest-lines').value.split('\n').map(s=>s.trim()).filter(Boolean),lift:$('suggest-kind').value==='lift'};if(!draft.ex.length)throw Error('Add at least one exercise or instruction.');const record=structuredClone(h.db().days[date]||{done:{},sets:{},notes:'',missed:false});applySuggestion(record,plan(date,h.db().start,h.db().days,resolveLongDay(h.db(),date)),draft,replace);h.commit(date,record);dialog.close();}catch(e){$('suggest-error').textContent=e.message;}};
$('suggest-close').onclick=()=>dialog.close();
}
