import {suggest,applySuggestion} from './suggestions.js?v=3.17.2';
import {plan,resolveLongDay} from './core.js?v=3.17.2';
export function mountSuggestions(h){const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const dialog=document.createElement('dialog');dialog.id='add-workout-dialog';dialog.innerHTML=`<form id="suggest-form"><h2>Add a workout</h2><p id="suggest-date"></p><label>Workout type<select id="suggest-type"><option value="full">Full-body lifting</option><option value="kettlebell">Kettlebells</option><option value="run">Running</option><option value="bike">Cycling</option><option value="recovery">Recovery / mobility</option><option value="hiit">HIIT Cycle</option><option value="plunge">Cold plunge</option></select></label><label>How to use it<select id="suggest-replace"></select></label><label>Workout name<input id="suggest-name" maxlength="500"></label><label class="remember"><input id="suggest-optional" type="checkbox"> Optional for this day</label><p id="suggest-error" role="alert"></p><div class="actions"><button id="suggest-save" class="primary" type="submit">Save to this date</button><button id="suggest-close" type="button">Cancel</button></div></form>`;document.body.append(dialog);const $=id=>dialog.querySelector('#'+id);let date,source,templateEx=[],templateLift=false;
function applyTemplate(){const replace=$('suggest-replace').value;const s=suggest(h.db(),date,{type:$('suggest-type').value,replace});$('suggest-name').value=s.name;$('suggest-optional').checked=s.optional??true;templateEx=s.ex;templateLift=s.lift;}
document.getElementById('add-workout').onclick=()=>{if(h.blocked())return;date=h.date();source=JSON.stringify(plan(date,h.db().start,h.db().days,resolveLongDay(h.db(),date)));$('suggest-date').textContent='For '+date;$('suggest-replace').innerHTML='<option value="">Add an optional extra workout</option>'+plan(date,h.db().start,h.db().days,resolveLongDay(h.db(),date)).map(t=>`<option value="${esc(t.id)}">Replace: ${esc(t.n)}</option>`).join('');$('suggest-error').textContent='';applyTemplate();dialog.showModal();};
$('suggest-type').onchange=applyTemplate;
$('suggest-replace').onchange=applyTemplate;
$('suggest-form').onsubmit=e=>{e.preventDefault();try{const replace=$('suggest-replace').value;if(h.blocked()||date!==h.date()||source!==JSON.stringify(plan(date,h.db().start,h.db().days,resolveLongDay(h.db(),date))))throw Error('History changed. Close and reopen Add a workout.');const draft={name:$('suggest-name').value,ex:templateEx,lift:templateLift,optional:$('suggest-optional').checked};if(!draft.name.trim())throw Error('Enter a workout name.');const record=structuredClone(h.db().days[date]||{done:{},sets:{},notes:'',missed:false});applySuggestion(record,plan(date,h.db().start,h.db().days,resolveLongDay(h.db(),date)),draft,replace);h.commit(date,record);dialog.close();}catch(e){$('suggest-error').textContent=e.message;}};
$('suggest-close').onclick=()=>dialog.close();
}
