import {today} from './core.js?v=3.16.2';
import {readiness} from './wellness.js?v=3.16.2';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const select=(id,label,options,value)=>`<label>${label}<select id="${id}"><option value="">Not recorded</option>${options.map(([v,t])=>`<option value="${v}" ${value===v?'selected':''}>${t}</option>`).join('')}</select></label>`;
export function renderWellness(h){const db=h.db(),date=h.date(),r=db.days[date]||{},p=db.profile||{},c=r.checkin||{};let box=document.getElementById('wellness');if(!box){box=document.createElement('section');box.id='wellness';box.className='card wellness';document.querySelector('.layout').after(box);}box.innerHTML=`<details><summary>Goals and availability</summary><form id="goals-form">${select('goal','Main priority',[['muscle','Muscle growth first'],['balanced','Balanced strength and endurance'],['endurance','Endurance first']],p.goal)}<label>Weekly time budget (hours)<input id="goal-hours" type="number" min="1" max="40" step="0.5" value="${esc(p.hours||'')}"></label><label>Preferred lifting days<input id="goal-days" maxlength="100" placeholder="Monday, Wednesday, Friday" value="${esc(p.days||'')}"></label>${select('goal-equipment','Usual equipment',[['gym','Full gym'],['db','Dumbbells'],['kb','Kettlebells'],['body','Bodyweight']],p.equipment)}<label>Activities to keep / schedule limits<textarea id="goal-limits" maxlength="500" placeholder="Saturday long ride; Wednesday only 30 minutes…">${esc(p.limits||'')}</textarea></label><p class="muted">These preferences guide your planning. Saving them does not move or rewrite existing workouts.</p><button ${h.blocked()?'disabled':''}>Save goals</button></form></details><details><summary>Daily check-in · ${esc(date)}</summary><form id="check-form"><fieldset ${h.blocked()||date>today()?'disabled':''}>${select('check-sleep','Sleep quality',[['good','Good'],['okay','Okay'],['poor','Poor']],c.sleep)}${select('check-energy','Energy',[['good','Good'],['okay','Okay'],['low','Low']],c.energy)}${select('check-stress','Stress',[['low','Low'],['moderate','Moderate'],['high','High']],c.stress)}${select('check-legs','Leg soreness',[['none','None'],['mild','Mild'],['high','Substantial']],c.legs)}${select('check-upper','Upper-body soreness',[['none','None'],['mild','Mild'],['high','Substantial']],c.upper)}${select('check-pain','Pain or illness (separate from soreness)',[['no','No'],['yes','Yes']],c.pain)}<button>Update check-in summary</button></fieldset></form><p>${esc(readiness(r.checkin))}</p></details><p id="wellness-status" role="status"></p>`;
const $=id=>box.querySelector('#'+id);function commit(fn,msg){if(h.blocked())return;fn();h.save();$('wellness-status').textContent=msg;}
$('goals-form').oninput=$('goals-form').onsubmit=e=>{e.preventDefault();if(e.type==='input'&&!e.target.validity.valid)return;commit(()=>{db.profile={goal:$('goal').value,hours:$('goal-hours').value,days:$('goal-days').value,equipment:$('goal-equipment').value,limits:$('goal-limits').value};},'Goals saved.');if(e.type==='submit')h.refresh();};
$('check-form').oninput=$('check-form').onsubmit=e=>{e.preventDefault();if(e.type==='input'&&!e.target.validity.valid)return;if(date>today())return;commit(()=>{const rec=db.days[date]||(db.days[date]={done:{},notes:'',sets:{}});rec.checkin=Object.fromEntries(['sleep','energy','stress','legs','upper','pain'].map(k=>[k,$('check-'+k).value]));},'Check-in saved.');if(e.type==='submit')h.refresh();};
}
